builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - "-s -w -X github.com/lunarway/shuttle/cmd.version={{.Version}} -X github.com/lunarway/shuttle/cmd.commit={{.Commit}}"

archive:
  format: binary
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  draft: true
  name_template: "v{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'