language: go

script: |
  echo "Build shuttle" &&
  go build &&
  ./shuttle run test

  # .travis.yml
language: go

services:
- docker

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux